### ISSUE TITLE
Does not work on node 5

### ISSUE THREAD

**Issue by felixSchl** [felixSchl/kopeer#4]
On node 5, running kopeer yields this error:

```
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at Object.exports.inherits (util.js:759:10)
    at Object.<anonymous> (/Users/felix/projects/kopeer/dist/Worker.js:96:19)
    at Module._compile (module.js:398:26)
   ... (another 100 lines or so) ...
```

**Comment by felixSchl** [comment]
Ah, well that was easy: f6d07407529cd49b3483ff9948fa20340e0c7227
